### ISSUE TITLE
"Function called outside component initialization" error in main branch

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/kit-docs-playground#2]
```
$ pnpm run dev

> mydocs@0.0.1 dev /home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs
> vite dev


  vite v2.9.14 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 853ms.

Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs:948:15)
    at Module.setContext (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs:978:5)
    at root.svelte:15:1
    at $$render (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs?v=db977724:1742:22)
    at Object.render (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs?v=db977724:1750:26)
    at render_response (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:1383:27)
    at async respond$1 (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:2996:4)
    at async resolve (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:3346:11)
    at async Object.handle (//home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/src/hooks:7:19)
    at async respond (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:3290:20)
(node:314886) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs:948:15)
    at Module.setContext (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs:978:5)
    at root.svelte:15:1
    at $$render (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs?v=db977724:1742:22)
    at Object.render (/node_modules/.pnpm/svelte@3.46.0/node_modules/svelte/internal/index.mjs?v=db977724:1750:26)
    at render_response (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:1383:27)
    at async respond_with_error (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:2758:10)
    at async respond$1 (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:3013:4)
    at async resolve (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/runtime/server/index.js:3346:11)
    at async Object.handle (//home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/src/hooks:7:19)
```

**Comment by stephane-klein** [comment]
Fixed by https://github.com/stephane-klein/kit-docs-playground/commit/3db48f35e0582790b328ec44b8711444ba447729

And by `https://github.com/svelteness/kit-docs/pull/60`
