### ISSUE TITLE
 Try to implement i18n support with docs/fr/page1.md filename pattern

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/kit-docs-playground#4]
I want to try to implement this i18n support:

```
/docs/en/page1.md
/docs/fr/page1.md
...
```

Resource:

- https://github.com/svelteness/kit-docs/issues/26

See also: https://github.com/stephane-klein/kit-docs-playground/issues/1

I will implement this feature in https://github.com/stephane-klein/kit-docs-playground/tree/4-i18n-folder-lang-extension branch.

**Comment by stephane-klein** [comment]
I have made good progress in https://github.com/stephane-klein/kit-docs-playground/tree/4-i18n-folder-lang-extension

Next task:

- [x] I look for how can I setup SvelteKit i18n support [here](https://github.com/stephane-klein/kit-docs-playground/blob/689e4bb0a635ac87f39d374187b9db82e52189cc/services/kit-docs/src/routes/__layout-kit-docs.svelte#L62)
    - [x] I need to read https://github.com/kaisermann/svelte-i18n
    - [x] I need to read https://github.com/sveltekit-i18n/lib

**Comment by stephane-klein** [comment]
[D'après ce commentaire](https://github.com/kaisermann/svelte-i18n/issues/166#issuecomment-994855870), j'ai l'impression que https://github.com/sveltekit-i18n/lib est  "plus à jour" que https://github.com/kaisermann/svelte-i18n

**Comment by stephane-klein** [comment]
In this commit, I setup `sveltekit-i18n` in `kit-docs`, but I have a but, this [French translations](https://github.com/stephane-klein/kit-docs-playground/blob/62e4bd250217c765f585f2c112f2ad2c07a3e08b/services/kit-docs/src/lib/translations/translations.js#L40) aren't used when I am on french page.

Todo:

- [x] Fix this bug

**Comment by stephane-klein** [comment]
> In this commit, I setup `sveltekit-i18n` in `kit-docs`, but I have a but, this [French translations](https://github.com/stephane-klein/kit-docs-playground/blob/62e4bd250217c765f585f2c112f2ad2c07a3e08b/services/kit-docs/src/lib/translations/translations.js#L40) aren't used when I am on french page.

Fixed by https://github.com/stephane-klein/kit-docs-playground/commit/6bc46e3d4a1d99ec9e56365c6e28f8d5275e3bc0

**Comment by stephane-klein** [comment]
Todo :

- [x] I want to fix this error:

```
stephane@nuc-i7:~/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs (4-i18n-folder-lang-extension) $ pnpm run build

> mydocs@0.0.1 build /home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs
> vite build

vite v2.9.14 building for production...
✓ 117 modules transformed.
.svelte-kit/output/client/_app/immutable/assets/Inter-VF.roman-latin-1b58736b.woff2                             51.24 KiB
.svelte-kit/output/client/_app/immutable/assets/Inter-VF.italic-latin-65279caf.woff2                            55.21 KiB
.svelte-kit/output/client/_app/immutable/assets/FiraCode-VF-05b30ba3.woff2                                      103.74 KiB
.svelte-kit/output/client/_app/immutable/assets/FiraCode-VF-71c5868a.woff                                       127.05 KiB
.svelte-kit/output/client/_app/manifest.json                                                                    7.07 KiB
.svelte-kit/output/client/_app/immutable/layout.svelte-4383708e.js                                              0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-d08cd36c.js                                               1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/__layout@kit-docs.svelte-bf94fec3.js                        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/en/_...1_first-category/_...2_second-page.md-4d4e9568.js    0.78 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/en/_...2_second-category/_...1_first-page.md-a047c366.js    0.78 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/en/_...2_second-category/_...2_second-page.md-ca15ec27.js   0.78 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/en/_...1_first-category/_...1_first-page.md-4587b1a2.js     14.64 KiB / gzip: 3.44 KiB
.svelte-kit/output/client/_app/immutable/start-e1b5df73.js                                                      28.61 KiB / gzip: 9.21 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/fr/_...1_first-category/_...2_second-page.md-bc77adae.js    0.78 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/fr/_...2_second-category/_...1_first-page.md-f4458948.js    0.78 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/fr/_...2_second-category/_...2_second-page.md-d6762502.js   0.78 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/fr/_...1_first-category/_...1_first-page.md-008f2456.js     14.64 KiB / gzip: 3.44 KiB
.svelte-kit/output/client/_app/immutable/pages/docs/index.svelte-6308b201.js                                    0.26 KiB / gzip: 0.21 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-e08b4eab.js                                          0.84 KiB / gzip: 0.51 KiB
.svelte-kit/output/client/_app/immutable/chunks/contexts-61b668f7.js                                            3.09 KiB / gzip: 1.33 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-7bd8f074.js                                               10.47 KiB / gzip: 4.17 KiB
.svelte-kit/output/client/_app/immutable/chunks/Link-17b5b1e4.js                                                0.82 KiB / gzip: 0.54 KiB
.svelte-kit/output/client/_app/immutable/assets/index-752e58c7.css                                              0.03 KiB / gzip: 0.05 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-81689fbf.js                                               14.71 KiB / gzip: 5.50 KiB
.svelte-kit/output/client/_app/immutable/pages/index@kit-docs.md-5fc51352.js                                    14.71 KiB / gzip: 5.12 KiB
.svelte-kit/output/client/_app/immutable/assets/pages/__layout-kit-docs.svelte-1ad07601.css                     53.00 KiB / gzip: 9.18 KiB
.svelte-kit/output/client/_app/immutable/pages/__layout-kit-docs.svelte-e3a20380.js                             101.19 KiB / gzip: 30.98 KiB
vite v2.9.14 building SSR bundle for production...
✓ 117 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                                                         6.07 KiB
.svelte-kit/output/server/index.js                                                              74.48 KiB
.svelte-kit/output/server/entries/endpoints/kit-docs/_slug_.meta.json.js                        0.12 KiB
.svelte-kit/output/server/entries/endpoints/kit-docs/_dir_.sidebar.json.js                      0.13 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js                                    0.25 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js                                     0.73 KiB
.svelte-kit/output/server/entries/pages/__layout-kit-docs.svelte.js                             88.64 KiB
.svelte-kit/output/server/entries/pages/docs/__layout@kit-docs.svelte.js                        0.27 KiB
.svelte-kit/output/server/entries/pages/docs/en/_...1_first-category/_...1_first-page.md.js     7.11 KiB
.svelte-kit/output/server/entries/pages/docs/en/_...1_first-category/_...2_second-page.md.js    0.67 KiB
.svelte-kit/output/server/entries/pages/docs/en/_...2_second-category/_...1_first-page.md.js    0.67 KiB
.svelte-kit/output/server/entries/pages/docs/en/_...2_second-category/_...2_second-page.md.js   0.67 KiB
.svelte-kit/output/server/entries/pages/docs/fr/_...1_first-category/_...1_first-page.md.js     7.11 KiB
.svelte-kit/output/server/entries/pages/docs/fr/_...1_first-category/_...2_second-page.md.js    0.67 KiB
.svelte-kit/output/server/entries/pages/docs/fr/_...2_second-category/_...1_first-page.md.js    0.67 KiB
.svelte-kit/output/server/entries/pages/docs/fr/_...2_second-category/_...2_second-page.md.js   0.67 KiB
.svelte-kit/output/server/entries/pages/docs/index.svelte.js                                    0.35 KiB
.svelte-kit/output/server/entries/pages/index@kit-docs.md.js                                    10.46 KiB
.svelte-kit/output/server/immutable/chunks/index-506eefd4.js                                    7.50 KiB
.svelte-kit/output/server/immutable/chunks/contexts-f09f441f.js                                 5.69 KiB
.svelte-kit/output/server/immutable/chunks/index-d51e169e.js                                    2.27 KiB
.svelte-kit/output/server/immutable/chunks/kitDocs-40d0796d.js                                  0.60 KiB
.svelte-kit/output/server/immutable/chunks/Link-2f7afb74.js                                     0.38 KiB
.svelte-kit/output/server/immutable/chunks/hooks-d259abab.js                                    0.00 KiB
TypeError: Cannot read properties of null (reading 'frontmatter')
    at load (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/output/server/entries/pages/__layout-kit-docs.svelte.js:1606:8)
    at async load_node (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/output/server/index.js:1595:14)
    at async respond$1 (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/output/server/index.js:1848:20)
    at async resolve (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/output/server/index.js:2175:114)
    at async respond (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/.svelte-kit/output/server/index.js:2130:22)
    at async visit (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.371_svelte@3.48.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1223:20)
(node:835422) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[vite-plugin-svelte-kit] 500 /docs
file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.371_svelte@3.48.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1122
                                throw new Error(format_error(details));
                                      ^

Error: 500 /docs
    at file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.371_svelte@3.48.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1122:11
    at save (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.371_svelte@3.48.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1341:4)
    at visit (file:///home/stephane/git/github.com/stephane-klein/kit-docs-playground/services/kit-docs/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.371_svelte@3.48.0+vite@2.9.14/node_modules/@sveltejs/kit/dist/vite.js:1232:3) {
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-svelte-kit',
  hook: 'writeBundle'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by stephane-klein** [comment]
> Todo :
> 
>     * [x]  I want to fix this error:
>

Error fixed, but translation don't works in SSG mode.

**Comment by stephane-klein** [comment]
> Error fixed, but translation don't works in SSG mode.

I think I have a lead: https://github.com/sveltekit-i18n/lib/blob/master/examples/locale-router-static/src/hooks.js

**Comment by stephane-klein** [comment]
>  Error fixed, but translation don't works in SSG mode.

Fixed by this change: https://github.com/stephane-klein/kit-docs-playground/commit/4a78f892106a774c3745e54024a0dbba394da685#r79987288
